export type ExportLang = "en" | "zh";

/** Labels for the PDF summary and CSV exports, kept as a small standalone
 * dictionary rather than sharing the web app's i18next setup — these run in
 * the Node server, not the browser, and only ever need this fixed set of
 * strings. Language is chosen by the caller (the web UI passes its current
 * locale), not stored per contract — there's no such field. */
export const exportLabels: Record<ExportLang, Record<string, string>> = {
  en: {
    summaryTitle: "Contract Summary",
    status: "Status",
    version: "Version",
    landlord: "Landlord",
    tenant: "Tenant",
    term: "Term",
    to: "to",
    renewalNotice: "Renewal notice",
    days: "days",
    units: "Units",
    from: "from",
    pricing: "Pricing",
    deposit: "Deposit",
    effective: "effective",
    yuan: "yuan",
    paymentLedger: "Payment ledger",
    billed: "billed",
    balance: "balance",
    overdue: "OVERDUE",
    amendmentHistory: "Amendment history",
    sqm: "sqm",
    draft: "Draft",
    active: "Active",
    expired: "Expired",
    terminated: "Terminated",
    rent: "Rent",
    management: "Management",
    electricity_base: "Electricity",
    water: "Water",
    elevator: "Elevator",
    other: "Other",
    flat: "Flat",
    per_sqm: "Per sqm",
    percentage_escalation: "Percentage escalation",
    per_month: "per month",
    per_quarter: "per quarter",
    per_year: "per year",
    per_sqm_per_month: "per sqm/month",
    csvReferenceNumber: "Reference number",
    csvLandlord: "Landlord",
    csvTenant: "Tenant",
    csvTermStart: "Term start",
    csvTermEnd: "Term end",
    csvStatus: "Status",
    csvVersion: "Version",
    csvServiceStart: "Service start",
    csvServiceEnd: "Service end",
    csvFeeType: "Fee type",
    csvDueDate: "Due date",
    csvBilledYuan: "Billed (yuan)",
    csvAllocatedYuan: "Allocated (yuan)",
    csvBalanceYuan: "Balance (yuan)",
    csvOverdueDays: "Overdue days",
  },
  zh: {
    summaryTitle: "合同摘要",
    status: "状态",
    version: "版本",
    landlord: "出租方",
    tenant: "承租方",
    term: "租期",
    to: "至",
    renewalNotice: "续租通知",
    days: "天",
    units: "单元",
    from: "起",
    pricing: "计价",
    deposit: "押金",
    effective: "生效于",
    yuan: "元",
    paymentLedger: "收付台账",
    billed: "应收",
    balance: "余额",
    overdue: "已逾期",
    amendmentHistory: "变更历史",
    sqm: "平方米",
    draft: "草稿",
    active: "生效中",
    expired: "已到期",
    terminated: "已终止",
    rent: "租金",
    management: "物业管理费",
    electricity_base: "电费",
    water: "水费",
    elevator: "电梯使用费",
    other: "其他",
    flat: "固定金额",
    per_sqm: "按平方米",
    percentage_escalation: "百分比递增",
    per_month: "每月",
    per_quarter: "每季度",
    per_year: "每年",
    per_sqm_per_month: "每平方米/月",
    csvReferenceNumber: "合同编号",
    csvLandlord: "出租方",
    csvTenant: "承租方",
    csvTermStart: "起租日",
    csvTermEnd: "到期日",
    csvStatus: "状态",
    csvVersion: "版本",
    csvServiceStart: "服务起始",
    csvServiceEnd: "服务结束",
    csvFeeType: "费用类型",
    csvDueDate: "到期日",
    csvBilledYuan: "应收（元）",
    csvAllocatedYuan: "已核销（元）",
    csvBalanceYuan: "余额（元）",
    csvOverdueDays: "逾期天数",
  },
};

export function resolveExportLang(value: unknown): ExportLang {
  return value === "zh" ? "zh" : "en";
}
